package com.company.classes;

public enum KindOfSport {
    BADMINTON, BASKETBALL, BASEBALL, BOXING, FREESTYLE_WRESTLING, GRECO_ROMAN_WRESTLING, CYCLING, WATER_POLO,
    VOLLEYBALL, BEACH_VOLLEYBALL, HANDBALL, SPORTS_GYMNASTICS, RHYTHMIC_GYMNASTICS, ROWING, ROWING_AND_CANOEING,
    ROWING_SLALOM_IN_KAYAKS_AND_CANOES, JUDO, HORSEBACK_RIDING, ATHLETICS, SAILING, SWIMMING, SYNCHRONIZED_SWIMMING,
    DIVING, TRAMPOLINING, MODERN_PENTATHLON, ARCHERY, BULLET_SHOOTING, TARGET_SHOOTING, TAEKWONDO, TENNIS, TABLE_TENNIS,
    TRIATHLON, WEIGHTLIFTING, FENCING, FOOTBALL, FIELD_HOCKEY, BIATHLON, SKIING, CURLING, SKATING, SKI_RACE,
    NORDIC_COMBINED, SKI_JUMPING, SNOWBOARD, FIGURE_SKATING, FREESTYLE, HOCKEY, SHORT_TRACK, ACROBATICS, AIKIDO,
    MOUNTAINEERING, ARMWRESTLING, AEROBICS_SPORTS, ILLIARD_SPORT, BODY_BUILDING, BOWLING, BRIDGE_SPORTS, WATER_SKIING,
    WEIGHT_LIFTING, GOROSHNY_SPORTS, DARTS, KARATE, KICKBOXING, MINI_FOOTBALL, ORIENTEERING_SPORTS, POWERLIFTING,
    FIRE_AND_RESCUE_SPORT, JUMPING_ON_THE_ACROBATIC_TRACK, HAND_TO_HAND_COMBAT, SAMBO, SPORT_CLIMBING, THAI_BOXING,
    DANCING_SPORTS, TOURISM, WUSHU, FOOTBALL_IN_THE_HALLS, CHESS, CHECKERS;
    }
